### ISSUE TITLE
Use actionlint-py wrapper

### ISSUE THREAD

**Issue by iainelder** [iainelder/aws-org-tree#8]
would like to use the wrapper to simplify the installation of dependencies in my GitHub workflows. In one of my projects, actionlint is the only dependency that isn't a Python package.

Wait for advice on staying up to date before using it: https://github.com/Mateusz-Grzelinski/actionlint-py/issues/1

**Comment by iainelder** [comment]
Project author has updated the wrapper to the latest version and is working on automating the updates.

I've added the wrapper in https://github.com/iainelder/aws-org-tree/commit/8ce7b501eed0aa5ebcac65796928ffefde3d9d97.

**Comment by Mateusz-Grzelinski** [comment]
I am preparing automating release in this PR. I wonder if it will work eventually... https://github.com/Mateusz-Grzelinski/actionlint-py/pull/3
Maybe you will find it usefull. I picked some things from your action, it came out pretty complicated.

**Comment by Mateusz-Grzelinski** [comment]
what I mean: if it stops working some time in the future, that will be my experiments gone bad

**Comment by iainelder** [comment]
Thanks for sharing! I guess we'll know for sure whether it works when a new version of actionlint is released.

**Comment by iainelder** [comment]
Learning how to configure my GitHub workflow for me was very much a trial-and-error process, with lots of deleting of tags and resources as I repated my testing. Experimentation is good!
